#auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: EmptY Blog
url: http://bupt-huxz.github.io
feed: /atom.xml
author_info: <a href="http://bupt-huxz.github.io/">EmptY</a>
